data:extend{
	{
		type="item",
		name="omni-chest",
		icon="__base__/graphics/icons/infinity-chest.png",
		icon_size=32,
		flags={"goes-to-quickbar"},
		subgroup="storage",
		order="a[items]-f[omni-chest]",
		place_result="omni-chest",
		stack_size=60000
	}
}